// @ts-nocheck
import "./styles/style.css";
import "./styles/purple.css";

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let state={kind:null,taskId:null,targets:[],reviews:[],selected:{},currentStep:1,maxStep:1};
function toast(s){let e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function busy(show,title='',text=''){let e=$('#busy');if(!e)return;e.classList.toggle('hidden',!show);if(title)$('#busyTitle').textContent=title;if(text)$('#busyText').textContent=text}
async function api(url,opt={}){let r=await fetch(url,opt),text=await r.text(),j;try{j=JSON.parse(text)}catch{throw Error(r.status===404?'当前端口运行的是旧版服务，请关闭旧窗口并重新启动工具':'服务器返回了无法识别的内容，请重启工具后再试')}if(!r.ok){let msg=j.error||'请求失败';if(msg.includes('批次已')||msg.includes('工具重启')){sessionStorage.clear();setTimeout(()=>{state={kind:null,taskId:null,targets:[],reviews:[],selected:{},currentStep:1,maxStep:1};location.href='/'},2200)}throw Error(msg)}return j}
function go(n){if(n<1||n>state.maxStep+1)return;state.currentStep=n;state.maxStep=Math.max(state.maxStep,n);$$('.panel').forEach(x=>x.classList.add('hidden'));$('#s'+n).classList.remove('hidden');$$('#steps li').forEach((x,i)=>{x.classList.toggle('active',i===n-1);x.classList.toggle('done',i<n-1);x.classList.toggle('available',i+1<=state.maxStep)});window.scrollTo({top:0,behavior:'smooth'});sessionStorage.setItem('cleanerStep',String(n))}
function addNavigation(){for(let n=2;n<=6;n++){let panel=$('#s'+n);if(!panel||panel.querySelector('.back-btn'))continue;let bar=document.createElement('div');bar.className='step-actions';let back=document.createElement('button');back.className='back-btn';back.type='button';back.textContent='← 返回上一步';back.onclick=()=>go(n-1);bar.appendChild(back);panel.insertBefore(bar,panel.firstChild)}$$('#steps li').forEach((li,i)=>li.onclick=()=>{if(i+1<=state.maxStep)go(i+1)})}
addNavigation();
api('/api/status').then(x=>{let missing=x.files.filter(f=>!f.exists);$('#health').textContent=missing.length?'缺少：'+missing.map(x=>x.name).join('、'):'4 个基础文件已就绪';$('#health').classList.toggle('ok',!missing.length)});
if(new URLSearchParams(location.search).has('download')){history.replaceState({},'', '/');setTimeout(()=>toast('下载链接无效或文件已移动，请在导出页重新生成'),300)}
$$('.type').forEach(b=>b.onclick=()=>{$$('.type').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.kind=b.dataset.kind;$('#create').disabled=false});
$('#create').onclick=async()=>{try{let x=await api('/api/task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:state.kind})});state.taskId=x.taskId;state.targets=x.headers;$('#batchName').textContent=(state.kind==='sale'?'出售':'出租')+' · '+state.taskId;go(2)}catch(e){toast(e.message)}};
$('#drop').onclick=()=>$('#drop input').click();$('#drop input').onclick=e=>e.stopPropagation();$('#drop input').onchange=e=>upload(e.target.files[0]);
$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files[0])};
async function upload(f){if(!f)return;busy(true,'正在上传并识别文件',`${f.name} · ${(f.size/1024/1024).toFixed(1)} MB，大文件可能需要几十秒`);try{let x=await api('/api/upload',{method:'POST',headers:{'X-Task-Id':state.taskId,'X-Filename':encodeURIComponent(f.name)},body:f});let received=x.received||{name:f.name,sizeMB:(f.size/1024/1024).toFixed(1)};$('#sheets').innerHTML=`<div class="notice"><b>服务器实际收到：</b>${received.name} · ${received.sizeMB} MB · ${x.sheets.length} 个工作表</div>`+x.sheets.map((s,i)=>`<div class="sheet"><div><b>${s.name}</b> ${s.hidden?'<em>隐藏</em>':''}<br><small>${s.rows} 条记录 · ${s.cols} 列 · 推测表头第 ${s.headerRow} 行</small></div><button class="primary choose" data-i="${i}">清洗此工作表</button><div class="preview">${s.preview.map(r=>r.join(' │ ')).join('<br>')}</div></div>`).join('');$$('.choose').forEach(b=>b.onclick=()=>selectSheet(x.sheets[+b.dataset.i]));toast('文件识别完成')}catch(e){toast(e.message)}finally{busy(false)}}
async function selectSheet(s){let btn=$$('.choose').find(b=>b.textContent.includes('清洗'));let old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent=`正在读取 ${Number(s.rows).toLocaleString()} 条数据…`}busy(true,'正在读取工作表',`${Number(s.rows).toLocaleString()} 条记录，请不要关闭页面`);try{let x=await api('/api/select-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:state.taskId,sheet:s.name,headerRow:s.headerRow})});state.targets=x.targets;$('#mapping').innerHTML=x.suggestions.map((m,i)=>`<tr><td><b>${m.source}</b></td><td><select data-source="${m.source}"><option value="__ignore__">不导入</option>${x.targets.map(t=>`<option ${t===m.target?'selected':''}>${t}</option>`).join('')}</select></td><td class="confidence">${Math.round(m.confidence*100)}%</td><td>${m.reason}</td><td>${m.samples.join(' / ')||'—'}</td></tr>`).join('');go(3);toast(`已读取 ${x.rows.toLocaleString()} 条记录`)}catch(e){toast(e.message)}finally{busy(false);if(btn){btn.disabled=false;btn.textContent=old}}}
$('#confirmMap').onclick=async()=>{let mapping={};$$('#mapping select').forEach(s=>mapping[s.dataset.source]=s.value);let btn=$('#confirmMap'),old=btn.textContent;btn.disabled=true;btn.textContent='正在匹配楼盘，请稍候…';try{let x=await api('/api/mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:state.taskId,mapping})});state.reviews=x.reviews;state.selected={};$('#estateReview').innerHTML=`<div class="notice">已自动可靠匹配 ${x.autoCount} 个小区、栋座及期名组合；${x.reviews.length} 个需要确认。同一小区的不同栋座会分别审核，可分别选择所属期名。</div>`+x.reviews.map((r,i)=>`<div class="review-card"><h3>${r.raw||'（空值）'} <small>原始栋座：${(r.buildings||[]).join('、')||'未填写'}</small>${r.phaseHint?` <small>期名提示：${r.phaseHint}</small>`:''}<small>影响 ${r.rows.length} 行</small></h3>${r.candidates.map(c=>`<label class="candidate"><input type="radio" name="rv${i}" data-key="${encodeURIComponent(r.key||r.raw)}" value="${encodeURIComponent(c.match_name||c.楼盘)}"><b>${c.match_name||c.楼盘}</b><span>${c.行政区} · ${c.商圈}</span><span>${c.期名||'无期名'} · ${c.别名||'无别名'}</span><span>${Math.round(c.score*100)}%</span></label>`).join('')}<label class="candidate"><input type="radio" name="rv${i}" data-key="${encodeURIComponent(r.key||r.raw)}" value=""><b>暂不匹配</b></label></div>`).join('');$$('#estateReview input[type=radio]').forEach(input=>input.onchange=()=>{let key=decodeURIComponent(input.dataset.key),value=input.value?decodeURIComponent(input.value):'';state.selected[key]=value;document.querySelectorAll(`input[name="${input.name}"]`).forEach(x=>x.closest('.candidate').classList.toggle('selected',x.checked));sessionStorage.setItem('estateSelections:'+state.taskId,JSON.stringify(state.selected))});go(4)}catch(e){toast(e.message)}finally{btn.disabled=false;btn.textContent=old}};
$('#confirmReview').onclick=async()=>{let btn=$('#confirmReview'),old=btn.textContent;btn.disabled=true;btn.textContent='正在检查栋座…';busy(true,'正在检查栋座','候选仅来自已确认楼盘的单元字典');try{let x=await api('/api/building-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:state.taskId,selected:state.selected||{}})});state.buildingReviews=x.reviews;state.buildingSelected={};$('#buildingReview').innerHTML=x.reviews.length?`<div class="notice">${x.reviews.length} 个栋座需要人工确认。选择一次会应用到同组记录。</div>`+x.reviews.map((r,i)=>`<div class="review-card"><h3>${r.estate} · 原始栋幢：${r.raw} <small>影响 ${r.rows.length} 行 · ${r.reason}</small></h3>${r.candidates.map(c=>`<label class="candidate"><input type="radio" name="br${i}" data-key="${encodeURIComponent(r.key)}" value="${encodeURIComponent(c)}"><b>${c}</b><span>字典标准栋座</span></label>`).join('')}<label class="candidate"><input type="radio" name="br${i}" data-key="${encodeURIComponent(r.key)}" value=""><b>暂不匹配</b></label></div>`).join(''):'<div class="notice">所有非空栋座均已唯一确认，无需人工处理。</div>';$$('#buildingReview input[type=radio]').forEach(input=>input.onchange=()=>{let key=decodeURIComponent(input.dataset.key);state.buildingSelected[key]=input.value?decodeURIComponent(input.value):'';document.querySelectorAll(`input[name="${input.name}"]`).forEach(x=>x.closest('.candidate').classList.toggle('selected',x.checked))});$('#entrust').value=new Date().toISOString().slice(0,10);go(5)}catch(e){toast(e.message)}finally{busy(false);btn.disabled=false;btn.textContent=old}};
$('#toExport').onclick=async()=>{try{await api('/api/building-confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:state.taskId,selected:state.buildingSelected||{},entrustDate:$('#entrust').value})});go(6)}catch(e){toast(e.message)}};
$$('.export').forEach(b=>b.onclick=async()=>{let old=b.textContent;try{b.disabled=true;b.textContent='正在生成…';let x=await api('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:state.taskId,cleanOnly:b.dataset.clean==='true'})});let href=x.downloadId?'/download/'+x.downloadId:(x.file?'/download/'+x.file.split(/[\\/]/).map(encodeURIComponent).join('/'):'');if(!href)throw Error('服务未返回下载地址，请重启工具后再试');$('#result').innerHTML=`<div class="result"><b>已生成 ${x.report.最终输出记录数} 条记录</b><p>阻断异常 ${x.report.阻断异常数量} 条 · 审计修改 ${x.audit} 条</p><a href="${href}">下载 Excel 导入文件</a></div>`;toast('文件已生成，请点击下载链接')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent=old}});
